### ISSUE TITLE
Unexpected end of line 147 in JSON file (Starfield 1.11.36 update)

### ISSUE THREAD

**Issue by Meridiano** [fo76utils/ce2utils#5]
Used build: https://github.com/fo76utils/ce2utils/actions/runs/9068312008 > build-win.zip

My actions (win cmd):
```
cd /d F:\Games\Starfield-Tools\ce2utils
mat_info -json -all F:\SteamLibrary\steamapps\common\Starfield\Data
```

Result:
```
... (many files are exported)
materials/setdressing/gentables/gentable_a01_wood01.mat
materials/setdressing/gentables/gentable_a01_wood01_yellow01.mat
materials/setdressing/gentables/gentable_a02_wood01.mat
materials/setdressing/gentables/gentable_b01_stainlesssteel01.mat
materials/setdressing/gentables/gentable_b01_stainlesssteel01_blue01.mat
materials/setdressing/gentables/gentable_b01_stainlesssteel01_green01.mat
materials/setdressing/gentables/gentable_c01_wood01.mat
materials/setdressing/gentables/gentable_c01_wood01_black.mat
materials/setdressing/gentables/gentable_d01_wood01.mat
mat_info: unexpected end of line 147 in JSON file
```

The utility stops then. I can press Enter and execution will be finished with no more files being exported.

Expected behavior: skip any bad file and continue exporting with the next one in list. Maybe log paths for bad files.

**Comment by fo76utils** [comment]
I will fix this issue soon, for now, you can work around it by adding the command line option -x:gentable_d01_wood01.mat after the game data path. There is another file that fails to load, but it only results in a warning.

**Comment by fo76utils** [comment]
Alternatively, you can replace the data path with the full path to the materials.ba2 file. This is actually recommended if you do not need the city map materials, because loading the main CDB file is more reliable than the files added by the SFBGS00* updates (which also replace all the base game materials).

**Comment by fo76utils** [comment]
An updated build that fixes the issue is now available. Note that I also disabled loading JSON format materials that would replace existing CDB materials and are in an archive. If you do want the .mat files in 'SFBGS007 - Main.ba2' to be processed, they currently need to be extracted to loose files.

**Comment by Meridiano** [comment]
I confirm the issue is fixed with the latest build ( https://github.com/fo76utils/ce2utils/actions/runs/9148885073 ). Thank you!
